### ISSUE TITLE
Error while running pico-wavsep using docker image 

### ISSUE THREAD

**Issue by rkhal101** [andresriancho/pico-wavsep#3]
To install wavsep I followed the instructions:
`git clone https://github.com/andresriancho/pico-wavsep.git`
`cd pico-wavsep`
`docker-compose up`

However, I get the following error on the terminal [look at attached file]. I'm running it on a kali vm.
[pico-wavsep-error.txt](https://github.com/andresriancho/pico-wavsep/files/1999385/pico-wavsep-error.txt)

**Comment by rkhal101** [comment]
I just tried it on the mac, and I get the same issue.

**Comment by andresriancho** [comment]
Confirmed, getting the same error. Let me investigage.

**Comment by andresriancho** [comment]
Fix https://github.com/andresriancho/pico-wavsep/commit/0adc64029750e6aa3c2025271c9f29111f530dfd

You'll have to delete all the old containers and then run `docker-compose up` again to get the 5.5 version of the mysql version
